"""add lat lng to venues

Revision ID: 94a33daf89c3
Revises: 1d6e345e4986
Create Date: 2026-05-02 01:15:11.928903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94a33daf89c3'
down_revision: Union[str, Sequence[str], None] = '1d6e345e4986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('venues', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'longitude')
    op.drop_column('venues', 'latitude')
    # ### end Alembic commands ###
